config/routes.rb
Rails.application.routes.draw do
 
  get 'message/create'
  root 'pages#home'
  
  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show', as: 'users'
  get '/creating_challenges', to: 'challenges#creating_challenges'
  get '/challenging_challenges', to: 'challenges#challenging_challenges'
  get '/challenges/:id', to: 'challenges#show', as: "challenge_detail"
  
  get '/all_requests', to: 'requests#list'
  get '/request_offers/:id', to: 'requests#offers', as: 'request_offers'
  get '/my_offers', to: 'requests#my_offers'
  get '/search', to: 'pages#search'
  get '/calendar', to: 'pages#calendar'
  get '/fixtures/:id/checkout/:detailing_type', to: 'fixtures#checkout', as: 'checkout'
  get '/conversations', to: 'conversations#list', as: "conversations"
  get '/conversations/:id', to: 'conversations#show', as: "conversation_detail"
 
 
 
  post '/users/edit', to: 'users#update'
  post '/offers', to: 'offers#create'
  post '/reviews', to: 'reviews#create'
  post 'messages', to: 'messages#create'
  post '/comments', to: 'comments#create'
  
  put '/creating_challenges/:id/accepted', to: 'challenges#accepted', as: 'challenge_accepted'
  put '/creating_challenges/:id/rejected', to: 'challengess#rejected', as: 'challenge_rejected'
  put '/offers/:id/accept', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'

  
  mount ActionCable.server => '/cable'
 
 
 resources :fixtures do
    member do
      delete :delete_photo
      post :upload_photo
    end
    resources :challenges, only: [:create]
  end
   
   resources :requests
   
  devise_for :users, 
              path: '', 
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
 
  
end

app/models/fixture.rb
class Fixture < ApplicationRecord
  belongs_to :user
  belongs_to :category

  has_many :detailings
  has_many :challenges
  has_many :reviews
  
  has_many_attached :photos
  has_rich_text :description

  accepts_nested_attributes_for :detailings

  validates :title, presence: { message: 'cannot be blank' }
  
  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:stars).round(1)
  end
end

app/controllers/fixtures_controller.rb
class FixturesController < ApplicationController
  
  protect_from_forgery except: [:upload_photo]
  before_action :authenticate_user!, except: [:show]
  before_action :set_fixture, except: [:new, :create]
  before_action :is_authorised, only: [:edit, :update, :upload_photo, :delete_photo]
  before_action :set_step, only: [:update, :edit]
  
  def new
    @fixture = current_user.fixtures.build
    @categories = Category.all
  end

   def create
    @fixture = current_user.fixtures.build(fixture_params)

    if @fixture.save
      @fixture.detailings.create(Detailing.detailing_types.values.map{ |x| {detailing_type: x} })
      redirect_to edit_fixture_path(@fixture), notice: "Save..."
    else
      redirect_to request.referrer, flash: { error: @fixture.errors.full_messages }
    end
   end

   def edit
    @categories = Category.all
   end

  def update

    if @step == 2
      fixture_params[:detailings_attributes].each do |index, detailing|
        if @fixture.has_single_detailing && detailing[:detailing_type] != Detailing.detailing_types.key(0)
          next;
        else
          if detailing[:title].blank? || detailing[:description].blank? || detailing[:match_time].blank? || detailing[:age].blank?
            return redirect_to request.referrer, flash: {error: "Invalid detail"}
          end
        end
      end
    end

    if @step == 3 && fixture_params[:description].blank?
      return redirect_to request.referrer, flash: {error: "Description cannot be blank"}
    end

    if @step == 4 && @fixture.photos.blank?
      return redirect_to request.referrer, flash: {error: "You don't have any photos"}
    end

    if @step == 5
      @fixture.detailings.each do |detailing|
        if @fixture.has_single_detailing && !detailing.mini?
          next;
        else
         if detailing[:title].blank? || detailing[:description].blank? || detailing[:match_time].blank? || detailing[:age].blank?
            return redirect_to edit_fixture_path(@fixture, step: 2), flash: {error: "Invalid detail"}
         end
        end
      end

      if @fixture.description.blank?
        return redirect_to edit_fixture_path(@fixture, step: 3), flash: {error: "Description cannot be blank"}
      elsif @fixture.photos.blank?
        return redirect_to edit_fixture_path(@fixture, step: 4), flash: {error: "You don't have any photos"}
      end
    end

    if @fixture.update(fixture_params)
      flash[:notice] = "Saved..."
    else
      return redirect_to request.referrer, flash: {error: @fixture.errors.full_messages}
    end

    if @step < 5
      redirect_to edit_fixture_path(@fixture, step: @step + 1)
    else
      redirect_to dashboard_path
    end

  end

  def show
    @categories = Category.all
  end
  
  def upload_photo
    @fixture.photos.attach(params[:file])
    render json: { success: true }
  end

  def delete_photo
    @image = ActiveStorage::Attachment.find(params[:photo_id])
    @image.purge
    redirect_to edit_fixture_path(@fixture, step: 4)
  end
  
 def checkout
      
   redirect_to checkout_path
 end
  
  private

  def set_step
    @step = params[:step].to_i > 0 ? params[:step].to_i : 1
    if @step > 5
      @step = 5
    end
  end
  
  
  def set_fixture
    @fixture = Fixture.find(params[:id])
  end

  def is_authorised
    redirect_to root_path, alert: "You do not have permission" unless current_user.id == @fixture.user_id
  end
  
  def fixture_params
    params.require(:fixture).permit(:title, :video, :description, :active, :category_id, :has_single_detailing, 
                                detailings_attributes: [:id, :title, :description, :match_time, :age, :detailing_type])
  end
end

app/helpers/fixtures_helper.rb
module FixturesHelper
end

app/views/fixtures/_checkout.html.erb
<section class="section">
    <div class="container">

        <%= form_with model: [@fixture, @fixture.challenges.new] do |f| %>
            <%= hidden_field_tag 'detailing_type', @detailing.detailing_type %>

            <div class="columns">

                <!-- LEFT SIDE -->
                <div class="column is-two-thirds">
                    <div class="columns is-multiline">
                        <div class="column is-full">
                            <div class="card">
                                <div class="card-content">
                                    <div class="content">
                                        <p class="title is-5">Payment options</p>
                                    </div>
                                    <hr>
                                    <div class="content">
                                        
                                                </span>
                                            </div>
                                        <% end %>
                                        <div class="control m-t-20">
                                            
                                        </div>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>


                <!-- RIGHT SIDE -->
                <div class="column">
                    <div class="columns is-multiline">
                        <div class="column is-full">
                            <div class="card">
                                <div class="card-content">
                                    <div class="content">
                                        <p class="title is-5">Summary</p>
                                    </div>
                                    <hr>
                                    <article class="media">
                                        <div class="media-content">
                                            <figure class="image is-4by3">
                                                <%= image_tag fixture_cover(@fixture) %>
                                            </figure>
                                        </div>
                                        <div class="media-right">
                                            <strong><%= @fixture.title %> </strong>
                                        </div>
                                    </article>

                                    <article class="media">
                                        <div class="media-content">
                                            Subtotal
                                        </div>
                                        <div class="media-right">
                                            
                                        </div>
                                    </article>

                                    <article class="media">
                                        <div class="media-content">
                                            
                                        </div>
                                        <div class="media-right">
                                            
                                        </div>
                                    </article>

                                    <article class="media">
                                        <div class="media-content">
                                            Total
                                        </div>
                                        <div class="media-right">
                                          
                                        </div>
                                    </article>

                                    <article class="media">
                                        <div class="media-content">
                                            Total delivery time
                                        </div>
                                        <div class="media-right">
                                            <%= pluralize(@detailing.match_time, 'day') %>
                                        </div>
                                    </article>
                                    
                                    <%= f.submit "Place Your Challenge", class: "button is-fullwidth is-danger", data: {confirm: "Are you sure?"} %>

                                </div>
                            </div>
                        
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</section>

app/views/fixtures/_step1.html.erb
<div class="step-content <%= 'is-active' if @step == 1 %>">
    <div class="field">
        <label class="label"><strong>Your Clubs Name </strong></label>
        <%= f.text_area :title, autocomplete: "title", class: "textarea" %>
    </div>
    <div class="field">
        <label class="label">Category</label>
        <%= f.select(:category_id, options_for_select(@categories.map{ |c| [c.name, c.id] }, selected: @fixture.category_id)) %>
    </div>
   
</div>

app/views/fixtures/_step2.html.erb
<div class="step-content <%= 'is-active' if @step == 2 %>">
    <div class="field">
        <div class="control">
            <div class="columns has-text-centered">

                <%= f.fields_for :detailings, @fixture.detailings.order(:detailing_type) do |p| %>
                    
                    <div class="column <%= 'is-3 is-offset-3' if @fixture.has_single_detailing && p.object.newmatch? %>
                 
                          
                        <label for="" class="label"> Create New Fixture</label>
                       

                        <div class="control">
                            <%= p.text_field :title, placeholder: "Club Name", class: "input is-radiusless" %>
                        </div>

                        <div class="control">
                            <%= p.text_area :description, placeholder: "Description of Fixture", class: "textarea is-radiusless" %>
                        </div>

                        <div class="control has-icons-right">
                            <%= p.number_field :match_time, placeholder: "Fixture is to be played in how many days ", class: "input is-radiusless", default: 1 %>
                            <span class="icon is-small is-right"></span>
                        </div>

                        <div class="control has-icons-right">
                            <%= p.number_field :age, placeholder: "The Team is Under 13's ", class: "input is-radiusless", default: 1 %>
                            <span class= "icon is-small is-right"></span>
                        </div>

                    </div>
                    
            <% end %>
             
            </div>
        </div>
     </div>
</div>

app/views/fixtures/_step3.html.erb
<div class="step-content <%= 'is-active' if @step == 3 %>">
    <div class="field">
        <label for="" class="label">Description</label>
        <%= f.rich_text_area :description, placeholder: "Give a description of your club or event " ,rows: 50, cols: 50 %>
    </div>
</div>

app/views/fixtures/_step4.html.erb
<div class="step-content <%= 'is-active' if @step == 4 %>">
    <div class="field">
        <label for="" class="label">Youtube Code</label>
        <%= f.text_field :video, autocomplete: "video url", class: "input" %>
    </div>

    <div class="field">
        <label for="" class="label">Build your Fixture Gallery</label>
        <div class="control">
            <div class="m-b-20">
                <div class="dropzone" id="myDropzone" action="/fixtures/<%= @fixture.id %>/upload_photo"></div>
            </div>

            <div class="columns is-multiline" style: width: 100%%>
                <% @fixture.photos.each do |photo| %>
                    <div class="column is-one-fifth">
                        <div class="card is-image">
                            <div class="card-image">
                                <%= link_to 'Remove', delete_photo_fixture_url(photo_id: photo.id, id: @fixture.id, step: @step), 
                                        method: :delete,
                                        data: { confirm: "Are you sure?" },
                                        class: "delete delete-file is-pulled-right",
                                        style: "z-index: 100"  %>

                                <figure class="image is-4by3">
                                    <%= image_tag url_for(photo) %>
                                </figure>
                            </div>
                        </div>
                    </div>

                <% end %>
            </div>
        </div>
    </div>
</div>

<script>
    Dropzone.options.myDropzone = {
        paramName: "file",
        maxFilesize: 2,
        acceptedFiles: "image/*",
        init: function() {
            this.on('complete', function (file) {
                location.reload();
            })
        }
    }
</script>

app/views/fixtures/_step5.html.erb
<div class="step-content has-text-centered <%= 'is-active' if @step == 5 %>">
    <div>
        <%= hidden_field_tag 'active', 'true' if @step == 5 %>
        <strong class="is-size-2">Almost there...</strong>
        <p>Let's publish your Fixture and get some challengers.</p>
    </div>
</div>

<div class="field is-grouped is-grouped-centered m-t-25">
    <p class="control <%= 'is-hidden' if @step <= 1 %>">
        <%= link_to 'Back', edit_fixture_path(@fixture, step: @step - 1), class: "button is-light" %>
    </p>

    <p class="control">
        <% if @step != 5 %>
            <%= f.submit 'Save & Continue', class: "button is-primary" %>
        <% else %>
            <%= link_to 'Publish', fixture_path(@fixture.id, fixture: {active: true}, step: @step), 
                        method: :put, 
                        data: {confirm: "Do you want to publish this fixture?"},
                        class: "button is-danger" %>
        <% end %>
    </p>
</div>

app/views/fixtures/edit.html.erb
<section class="section">
  <div class="container">
    <div class="steps" id="stepsDemo">

      <!-- 5 STEPS -->
      <div class="step-item <%= 'is-active' if @step == 1 %> <%= 'is-completed' if @step > 1 %>">
        <div class="step-marker">1</div>
        <div class="step-details">
          <p class="step-title">Overview</p>
        </div>
      </div>
      <div class="step-item <%= 'is-active' if @step == 2 %> <%= 'is-completed' if @step > 2 %>">
        <div class="step-marker">2</div>
        <div class="step-details">
          <p class="step-title">Details</p>
        </div>
      </div>
      <div class="step-item <%= 'is-active' if @step == 3 %> <%= 'is-completed' if @step > 3 %>">
        <div class="step-marker">3</div>
        <div class="step-details">
          <p class="step-title">Description</p>
        </div>
      </div>
      <div class="step-item <%= 'is-active' if @step == 4 %> <%= 'is-completed' if @step > 4 %>">
        <div class="step-marker">4</div>
        <div class="step-details">
          <p class="step-title">Gallery</p>
        </div>
      </div>
      <div class="step-item <%= 'is-active' if @step == 5 %> <%= 'is-completed' if @step > 5 %>">
        <div class="step-marker">5</div>
        <div class="step-details">
          <p class="step-title">Publish</p>
        </div>
      </div>

      <!-- FORM TO CREATE A NEW FIXTURE HERE-->
      <%= form_for @fixture, html: {class: "steps-content m-l-100 m-r-100"} do |f| %>
        <%= hidden_field_tag 'step', @step %>
        
        <%= render 'step1', f: f %>
        <%= render 'step2', f: f %>
        <%= render 'step3', f: f %>
        <%= render 'step4', f: f %>
        <%= render 'step5', f: f %>

      <% end %>
    </div>
  </div>
</section>

app/views/fixtures/new.html.erb
<div class="step-content <%= 'is-active' if @step == 1 %>">
<section class="section">
  <div class="container">
    <div class="steps" id="stepsDemo">

      <!-- 5 STEPS -->
      <div class="step-item is-active is-primary">
        <div class="step-marker">1</div>
        <div class="step-details">
          <p class="step-title">Overview</p>
        </div>
      </div>
      <div class="step-item">
        <div class="step-marker">2</div>
        <div class="step-details">
          <p class="step-title">Details</p>
        </div>
      </div>
      <div class="step-item">
        <div class="step-marker">3</div>
        <div class="step-details">
          <p class="step-title">Description</p>
        </div>
      </div>
      <div class="step-item">
        <div class="step-marker">4</div>
        <div class="step-details">
          <p class="step-title">Gallery</p>
        </div>
      </div>
      <div class="step-item">
        <div class="step-marker">5</div>
        <div class="step-details">
          <p class="step-title">Publish</p>
        </div>
      </div>

      <!-- FORM TO CREATE A NEW FIXTURE HERE-->
      <%= form_for @fixture, html: {class: "steps-content m-l-100 m-r-100"} do |f| %>
        <div class="field">
             <label class="label"><strong>Your Clubs Name </strong></label>
            <%= f.text_area :title, autocomplete: "title", class: "textarea" %>
        </div>
        <div class="field">
            <label class="label">Category</label>
            <%= f.select(:category_id, options_for_select(@categories.map{ |c| [c.name, c.id] })) %>
        </div>
        <div class="field is-grouped is-grouped-centered m-t-25">
           <a href="" data-nav="previous" class="button is-light">Cancel</a>
            <%= f.submit "Save & Continue", class: "button is-primary" %>
        </div>

      <% end %>
    </div>
  </div>

</section>
 </div>

app/views/fixtures/show.html.erb
<% content_for :head do %>
  <meta name="turbolinks-cache-control" content="no-cache">
<% end %>

<%= render 'shared/categories' %>

<section class="section">
    <div class="container">
        <div class="columns">

            <!-- LEFT SIDE -->
            <div class="column is-two-thirds">
                <div class="columns is-multiline">

                    <!-- Carousel -->
                    <div class="column is-full">   
                        <div class="card">
                            <div class="card-content">
                                <div class="content">
                                    <p class="title is-4"><%= @fixture.title %></p>
                                </div>
                                <hr>
                                <div class="hero-carousel" id="carousel-photo">
                                    <% @fixture.photos.each do |photo| %>
                                        <div class="carousel-item has-background image is-16by9">
                                            <%= image_tag url_for(photo), class: "is-background", width: "100%" %>
                                        </div>
                                    <% end %>
                                    <% if @fixture.video.present? %>
                                        <div class="video-container">
                                            <iframe src="https://www.youtube.com/embed/<%= @fixture.video %>" allowfullscreen></iframe>
                                        </div>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- About Section -->
                    <div class="column">
                        <div class="card">
                            <div class="card-content">
                                <article class="media">
                                    <div class="media-content">
                                        <p><strong>About This Fixture</strong></p>
                                        <hr>
                                        <%= @fixture.description %>
                                    </div>
                                </article>
                            </div>
                        </div>                        
                    </div>
                    
                </div>
            </div>

            <!-- RIGHT SIDE -->
            <div class="column">
                <div class="columns is-multiline">

                    <!-- Detailing Section -->
                    <div class="column is-full">

                        <div class="tabs is-fullwidth" id="tabs">
                            <ul>
                                <% Detailing.detailing_types.each do |key, value| %>
                                    <li class="tab <%= 'is-active' if value == 0 %> " 
                                                data-tab="<%= key %>" style="<%= 'display: none' if @fixture.has_single_detailing && value != 0 %>">
                                        <a><%= key.capitalize %></a>
                                    </li>
                                <% end %>
                            </ul>
                        </div>

                        <div class="tabs-content">

                            <% @fixture.detailings.each do |d| %>
                                <div class="tab-content" id="tab-<%= d.detailing_type %>" style="<%= 'display: none' if !d.fixture? %>">
                                    <div class="card">
                                        <div class="card-content">
                                          
                                                <div class="media">
                                                     
                                                    <strong>  <p class="title is-5"><%= d.title %></p></strong> 
                                                </div>
                                                <div class="media-content">
                                                    <p class="title is-6">Under <%= d.age %>'s</p>
                                                                                            
                                            </div>
                                            <div class="content f-15">
                                                <p class="m-t-30"><%= d.description %></p>
                                                <p class="m-t-30">
                                                    <strong><i class="far fa-clock"></i> In the next <%= pluralize(d.match_time, 'day') %> </strong>                                                    
                                                </p>
                                            </div>
                                            <% if (!user_signed_in? && @fixture.active) || (user_signed_in? && @fixture.active && @fixture.user_id != current_user.id) %>
 <%= form_for([@fixture, @fixture.challenges.new]) do |f| %>
 <%=hidden_field_tag 'detailing_type', d.detailing_type%>
 <%=f.submit "Challenge",class: "button is-fullwidth is-danger", data: {confirm:"are you sure?"}%>
 <% end %>
 <% else %>
          <button class="button is-fullwidth is-danger" disabled>Not Available</button>  
 <% end %>
                                            
                                        </div>
                                    </div>
                                </div>
                            <% end %>
                        </div>

                    </div>

                    <!-- Profile Section -->
                    <div class="column">
                        <div class="card">
                            <div class="card-content is-horizontal-center is-flex">
                                <%= link_to users_path(@fixture.user) do %>
                                    <figure class="image is-96x96">
                                        <%= image_tag avatar_url(@fixture.user), class: "is-rounded" %>
                                    </figure>
                                <% end %>
                            </div>
                            <div class="card-content f-15">
                                <div class="content has-text-centered">
                                    <p class="title is-5"><%= @fixture.user.full_name %></p>
                                        <% if current_user.id != @fixture.user.full_name%>
                                        <a class="button is-black is-outlined is-fullwidth toggle-contact">Contact Me</a>
                                        <% end %>
                                </div>
                                <article class="media">
                                    <div class="media-content">
                                        <i class="fas fa-user m-r-5"></i> Member since
                                    </div>
                                    <div class="media-right">
                                        <%= @fixture.user.created_at.strftime('%b %Y') %>
                                    </div>
                                </article>
                                <article class="media">
                                    <div class="media-content">
                                        <i class="fas fa-map-marker-alt m-r-5"></i> From
                                    </div>
                                    <div class="media-right">
                                        <%= @fixture.user.from %>
                                    </div>
                                </article>
                                <article class="media">
                                    <div class="media-content">
                                        <%= @fixture.user.about %>
                                    </div>
                                </article>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="modal" id="contact-form">
    <div class="modal-background"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title">Send a Message</p>
            <button class="delete toggle-contact" aria-label="close"></button>
        </header>
        <section class="modal-card-body">
            <div class="columns">
                <div class="column is-one-third">
                    <div class="card">
                        <div class="card-content is-horizontal-center is-flex">
                            <figure class="image is-128x128">
                                <%= image_tag avatar_url(@fixture.user), class: "is-rounded" %>
                            </figure>
                        </div>
                        <div class="card-content">
                            <hr>
                            <strong>Please include:</strong>
                            <ul class="is-size-7" style="list-style:initial">
                                <li>Any Questions you have about this fixture</li>
                                <li>along with some details about your Team</li>
                                <li>your time frame & location</li>
                            </ul>
                        </div>
                     </div>
                </div> 
                  
                
                <div class="column">
                    <%= form_with model: Message.new do |f| %>
                        <%= f.hidden_field :receiver_id, value: @fixture.user.id %>
                        <div class="card-content">
                            <div class="field">
                                <div class="control">
                                    <%= f.text_area :content, class: "textarea" %>
                                </div>
                                
                                
                                
                            </div>
                            <%= f.submit "Send", class: "button is-danger is-pulled-right" %>
                        </div>
                    <% end %>
                </div>
            </div>
        </section>
    </div>
</div>
<script>
    var toggle_modals = $('.toggle-contact');
    if (toggle_modals) {
        toggle_modals.on('click', function(event) {
            event.stopPropagation();
            event.preventDefault();
            var form = document.getElementById('contact-form');
            form.classList.toggle('is-active');
        });
    }
</script>


<script>
    BulmaCarousel.attach('#carousel-photo', {
        slidesToScroll: 1,
        slidesToShow: 1
    });

    $(document).ready(function() {
        $('#tabs li').on('click', function() {
            var type = $(this).data('tab');

            $('#tabs li').removeClass('is-active');
            $(this).addClass('is-active');

            $('.tab-content').hide();
            $('#tab-' + type).show();
        }) 
    })

</script>