config/routes.rb
Rails.application.routes.draw do
 
  get 'message/create'
  root 'pages#home'
  
  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show', as: 'users'
  get '/creating_challenges', to: 'challenges#creating_challenges'
  get '/challenging_challenges', to: 'challenges#challenging_challenges'
  get '/challenges/:id', to: 'challenges#show', as: "challenge_detail"
  
  get '/all_requests', to: 'requests#list'
  get '/request_offers/:id', to: 'requests#offers', as: 'request_offers'
  get '/my_offers', to: 'requests#my_offers'
  get '/search', to: 'pages#search'
  get '/calendar', to: 'pages#calendar'
  get '/fixtures/:id/checkout/:detailing_type', to: 'fixtures#checkout', as: 'checkout'
  get '/conversations', to: 'conversations#list', as: "conversations"
  get '/conversations/:id', to: 'conversations#show', as: "conversation_detail"
 
 
 
  post '/users/edit', to: 'users#update'
  post '/offers', to: 'offers#create'
  post '/reviews', to: 'reviews#create'
  post 'messages', to: 'messages#create'
  post '/comments', to: 'comments#create'
  
  put '/creating_challenges/:id/accepted', to: 'challenges#accepted', as: 'challenge_accepted'
  put '/creating_challenges/:id/rejected', to: 'challengess#rejected', as: 'challenge_rejected'
  put '/offers/:id/accept', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'

  
  mount ActionCable.server => '/cable'
 
 
 resources :fixtures do
    member do
      delete :delete_photo
      post :upload_photo
    end
    resources :challenges, only: [:create]
  end
   
   resources :requests
   
  devise_for :users, 
              path: '', 
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
 
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  has_one_attached :avatar
  has_many :fixtures
  has_many :requests
  has_many :offers
  
  has_many :challenging_challenges, foreign_key: "challenger_id", class_name: "Challenge"
  has_many :creating_challenges, foreign_key: "creator_id", class_name: "Challenge"
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable
         
  validates :full_name, presence: true, length: {maximum: 50}       


  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first

    if user
      if !user.provider
        user.update(uid: auth.uid, provider: auth.provider, image: auth.info.image)
      end
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.full_name = auth.info.name   # assuming the user model has a name
        user.image = auth.info.image # assuming the user model has an image

        user.uid = auth.uid
        user.provider = auth.provider

      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def dashboard
  end

 def show
    @user = User.find(params[:id])
    @reviews = Review.where(creator_id: params[:id]).challenge("created_at desc")
 end

  def update
    @user = current_user
    if @user.update_attributes(current_user_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Cannot update..."
    end
    redirect_to dashboard_path
  end

 def update_checkout
    if !current_user.checkout_id
      customer = Checkout::Customer.create(
        email: current_user.email,
        source: params[:user_id]
      )
    else
      customer = Checkout::Customer.update(
        current_user.checkout_id,
     source: params[:user_id]
      )
    end

end
    private
    
      def current_user_params
        params.require(:user).permit(:from, :about, :status, :team, :avatar)
      end
 end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/dashboard.html.erb
<section class="section">
    <div class="container">
        <div class="columns">
        
            <!-- LEFT SIDE -->
            <div class="column is-one-third">
                <div class="columns is-multiline">

                    <!-- Top Card -->
                    <div class="column is-full">
                        <div class="card">

                            <!-- Avatar -->
                            <div class="card-content is-horizontal-center is-flex">
                                <figure class="image is-128x128">
                                    <%= image_tag avatar_url(current_user), class: "is-rounded" %>
                                </figure>
                            </div>
                            
                            <div class="card-content">

                                <!-- Upload Button -->
                                <div class="content has-text-centered">
                                    <p class="title is-5"><%= current_user.full_name %></p>
                                    <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post do |f| %>
                                        <div class="file">
                                            <label class="button is-primary is-outlined is-fullwidth">
                                                <%= f.file_field :avatar, class: "file-input", onchange: "this.form.submit();" %>
                                                <i class="fas fa-upload"></i>&nbsp;&nbsp;&nbsp; Upload Avatar
                                            </label>
                                        </div>
                                    <% end %>
                                </div>
                                <hr class="h-10">
                                
                                <!-- Member -->
                                <article class="media">
                                    <div class="media-content">Member since</div>
                                    <div class="media-right">
                                        <strong><%= current_user.created_at.strftime('%b %Y') %></strong>
                                    </div>
                                </article>
                                <hr class="h-10">
                                
                                <!-- From -->
                                <article>
                                    <div class="media">
                                        <div class="media-content">From</div>
                                        <div class="media-right">
                                            <strong><%= current_user.from %></strong> <i class="toggle far fa-edit" aria-controls="user-from"></i>
                                        </div>
                                    </div>

                                    <div class="content">
                                        <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-from', class: 'is-hidden'} do |f| %>
                                            <div class="field">
                                                <%= f.text_field :from, autofocus: true, autocomplete: 'form', class: 'input'%>
                                            </div>
                                            <a class="toggle button is-light" aria-controls="user-from">Cancel</a>
                                            <%= f.submit "Save", class: "button is-danger" %>
                                        <% end %>
                                    </div>

                                </article>                                
                                <hr class="h-10">

                                <!-- Online Status -->
                                <article>
                                    <div class="media">
                                        <div class="media-content">Online Status</div>
                                        <div class="media-right">
                                            <strong><% if current_user.status %> Online <% else %> Offline <% end %></strong> <i class="toggle far fa-edit" aria-controls="user-status"></i>
                                        </div>
                                    </div>

                                    <div class="content">
                                        <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-status', class: 'is-hidden'} do |f| %>
                                            <div class="field">
                                                <%= f.select(:status, options_for_select([["Online", true], ["Offline", false]]), {}, {class: "select is-fullwidth"}) %>
                                            </div>
                                            <a class="toggle button is-light" aria-controls="user-status">Cancel</a>
                                            <%= f.submit "Save", class: "button is-danger" %>
                                        <% end %>
                                    </div>
                                </article>
                                
                           </div>
                        </div>
                    </div>

                    <!-- Bottom Card -->
                    <div class="column is-full">
                        <div class="card">
                            <div class="card-content">

                                <!-- About -->
                                <article>
                                    <div class="media">
                                        <div class="media-content">
                                            <p>
                                                <strong>About Yourself</strong>
                                                <br>
                                                <%= current_user.about %>
                                            </p>
                                        </div>
                                        <div class="media-right">
                                            <i class="toggle far fa-edit" aria-controls="user-about"></i>
                                        </div>
                                    </div>

                                    <div class="content">
                                        <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-about', class: 'is-hidden'} do |f| %>
                                            <div class="field">
                                                <%= f.text_area :about, autofocus: true, autocomplete: 'form', class: 'input'%>
                                            </div>
                                            <a class="toggle button is-light" aria-controls="user-about">Cancel</a>
                                            <%= f.submit "Save", class: "button is-danger" %>
                                        <% end %>
                                    </div>
                                </article>
                                <hr class="h-10">

                                <!-- Team -->
                                <article>
                                    <div class="media">
                                        <div class="media-content">
                                            <p>
                                                <strong>Team</strong>
                                                <br>
                                                <%= current_user.team %>
                                            </p>
                                        </div>
                                        <div class="media-right">
                                            <i class="toggle far fa-edit" aria-controls="user-team"></i>
                                        </div>
                                    </div>

                                    <div class="content">
                                        <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-team', class: 'is-hidden'} do |f| %>
                                            <div class="field">
                                                <%= f.text_field :team, autofocus: true, autocomplete: 'form', class: 'input'%>
                                            </div>
                                            <a class="toggle button is-light" aria-controls="user-team">Cancel</a>
                                            <%= f.submit "Save", class: "button is-danger" %>
                                        <% end %>
                                    </div>

                                </article>
                                <hr class="h-10">
                                
                                <!-- Linked Account -->
                                <article class="media">
                                    <div class="content">
                                        <p>
                                            <strong>Linked Account</strong><br/>
                                            <% if current_user.provider %>
                                                <span class="has-text-success">Facebook verified</span>
                                            <% else %>
                                                <%= link_to 'Connect to Facebook', user_facebook_omniauth_authorize_path, class: "has-text-danger" %>
                                            <% end %>
                                        </p>
                                    </div>
                                </article>
                                <hr class="h-10">

                                <!-- Mobile Number -->
                               

                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <!-- RIGHT SIDE -->
            <div class="column">
                <div class="columns is-multiline">

                    <!-- Create New Fixture -->
                    <div class="column is-one-third has-text-centered">
                        <%= link_to new_fixture_path do %>
                            <div class="card">

                                <div class="card-image card-content is-horizontal-center is-flex ">
                                    <figure class="image is-128x128 ">
                                        <%= image_tag 'icon_add.png' %>
                                    </figure>
                                </div>

                                <div class="card-content">
                                    <strong>Create a New Fixture</strong>
                                </div>    

                            </div>
                        <% end %>
                    </div>


                    <!-- Sample fixture -->
                    <% current_user.fixtures.each do |fixture| %>

                        <div class="column is-one-third">
                            <div class="card">

                                <div class="card-image">
                                    <%= link_to edit_fixture_path(fixture) do %>
                                        <figure class="image is-4by3">
                                            <%= image_tag fixture_cover(fixture) %>
                                        </figure>
                                    <% end %>
                                </div>

                                <div class="card-content p-t-5 p-b-5">
                                    <p class="subtitle is-6 m-b-5"><%= link_to fixture.title, fixture_path(fixture) %></p>
                                    <span class="star-review"><i class="fa fa-star"></i>
                                        <%= fixture.average_rating %>
                                        <span class="has-text-primary">(<%= fixture.reviews.count %>)</span>
                                    </span>                                        
                                </div>

                                <footer class="card-footer">
                                    <% mini_age = fixture.detailings.find{ |p| p.detailing_type == 'mini' } %>

                                    <a class="has-text-danger is-block card-footer-item has-text-right">
                                        <% if !mini_age.nil? %>
                                            <span class="small-title">Age Group:</span> <br>
                                            <strong>Under : <%=mini_age.age %>'s </strong>                                            
                                        <% else %>
                                                <span class="small-title has-text-dark">NO detail YET</span>
                                            </strong>
                                        <% end %>
                                    </a>
                                </footer>  
                                
                            </div>
                        </div>

                    <% end %>
                    
                </div>
            </div>
            
        </div>
    </div>
</section>



    

app/views/users/show.html.erb
<section class="section">
    <div class="container">
        <div class="columns">
        
            <!-- LEFT SIDE -->
            <div class="column is-one-third">
                <div class="columns is-multiline">

                    <!-- Top Card -->
                    <div class="column is-full">
                        <div class="card">

                            <!-- Avatar -->
                            <div class="card-content is-horizontal-center is-flex">
                                <figure class="image is-128x128">
                                    <%= image_tag avatar_url(@user), class: "is-rounded" %>
                                </figure>
                            </div>
                            
                            <div class="card-content">

                                <!-- Upload Button -->
                                <div class="content has-text-centered">
                                    <p class="title is-5"><%= @user.full_name %></p>
                                    <% if current_user.id != @user.id %>
                                      <a class="button is-black is-outlined is-fullwidth toggle-contact">Contact Me</a>
                                    <% end %>
                                </div>
                                <hr class="h-10">
                                
                                <!-- Member -->
                                <article class="media">
                                    <div class="media-content">Member since</div>
                                    <div class="media-right">
                                        <strong><%= @user.created_at.strftime('%b %Y') %></strong>
                                    </div>
                                </article>
                                <hr class="h-10">
                                
                                <!-- From -->
                                <article class="media">
                                    <div class="media-content">From</div>
                                    <div class="media-right">
                                        <strong><%= @user.from %></strong>
                                    </div>
                                </article>                                
                                <hr class="h-10">

                                <!-- Online Status -->
                                <article class="media">
                                    <div class="media-content">Online Status</div>
                                    <div class="media-right">
                                        <strong><% if @user.status %> Online <% else %> Offline <% end %></strong>
                                    </div>
                                </article>

                            </div>
                        </div>
                    </div>

                    <!-- Bottom Card -->
                    <div class="column is-full">
                        <div class="card">
                            <div class="card-content">

                                <!-- About -->
                                <article class="media">
                                    <div class="media-content">
                                        <p>
                                            <strong>About Yourself</strong>
                                            <br>
                                            <%= @user.about %>
                                        </p>
                                    </div>
                                </article>
                                <hr class="h-10">

                                <!-- Team -->
                                <article class="media">
                                    <div class="media-content">
                                        <p>
                                            <strong>Team</strong>
                                            <br>
                                            <%= @user.team %>
                                        </p>
                                    </div>
                                </article>
                                <hr class="h-10">
                                
                                <!-- Linked Account -->
                                <article class="media">
                                    <div class="content">
                                        <p>
                                            <strong>Linked Account</strong><br/>
                                            <% if @user.provider %>
                                                <span class="has-text-success">Facebook verified</span>
                                            <% else %>
                                                <span class="has-text-danger">Facebook unverified</span>
                                            <% end %>
                                        </p>
                                    </div>
                                </article>
                                
               <!-- Mobile Number -->
                               </div>
                        </div>
                    </div>

                </div>
            </div>         

            <!-- RIGHT SIDE -->
            <div class="column">

                <div class="columns is-multiline">
                    <!-- Sample Fixture -->
                    <% @user.fixtures.each do |fixture| %>

                        <div class="column is-one-third">
                            <div class="card">

                                <div class="card-image">
                                    <%= link_to edit_fixture_path(fixture) do %>
                                        <figure class="image is-4by3">
                                            <%= image_tag fixture_cover(fixture) %>
                                        </figure>
                                    <% end %>
                                </div>

                                <div class="card-content p-t-5 p-b-5">
                                    <p class="subtitle is-6 m-b-5"><%= link_to fixture.title, fixture_path(fixture) %></p>
                                    <span class="star-review"><i class="fa fa-star"></i>
                                        <%= fixture.average_rating %>
                                        <span class="has-text-primary">(<%= fixture.reviews.count %>)</span>
                                    </span>                                        
                                </div>

                              <footer class="card-footer">
                                    <% mini_age = fixture.detailings.find{ |p| p.detailing_type == 'mini' } %>

                                    <a class="has-text-danger is-block card-footer-item has-text-right">
                                        <% if !mini_age.nil? %>
                                            <span class="medium-title">Age Group : Under</span> 
                                            <strong><%=mini_age.age %>'S </strong>                                            
                                        <% else %>
                                            <strong>
                                                <span class="small-title has-text-dark">NO detail YET</span>
                                            </strong>
                                        <% end %>
                                    </a>
                                </footer>  
                                
                            </div>
                        </div>

                    <% end %>
                </div>


                <div class="card">
                    <div class="card-header">
                        <div class="card-header-title">Latest Reviews</div>
                    </div>
                    <div class="card-content">

                        <!-- Sample Reviews -->
                        <% @reviews.each do |r| %>
                            <article class="media">
                                <figure class="media-left">
                                    <p class="image is-64x64">
                                        <%= image_tag avatar_url(r.challenger), class: "is-rounded" %>
                                    </p>
                                </figure>

                                <div class="media-content">
                                    <div class="content">
                                        <p>
                                            <strong><%= r.challenger.full_name %></strong><br>
                                            <%= r.review %>
                                        </p>
                                        <small><%= time_ago_in_words(r.created_at) %></small>
                                    </div>
                                </div>

                                <div class="media-right">
                                    <span class="star-review"><i class="fa fa-star"></i><%= r.stars %></span>
                                </div>

                            </article>
                        <% end %>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</section>

<div class="modal" id="contact-form">
    <div class="modal-background"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title">Send a Message</p>
            <button class="delete toggle-contact" aria-label="close"></button>
        </header>
        <section class="modal-card-body">
            <div class="columns">
                <div class="column is-one-third">
                    <div class="card" st>
                        <div class="card-content is-horizontal-center is-flex">
                            <figure class="image is-128x128">
                                <%= image_tag avatar_url(@user), class: "is-rounded" %>
                            </figure>
                        </div>
                        <div class="card-content">
                            <hr>
                            <strong>Please include:</strong>
                            <ul class="is-size-7" style="list-style:initial">
                                <li>Fixture description</li>
                                <li>Specific instructions</li>
                                <li>Relevant files</li>
                                <li>Your Time Frame</li>
                            </ul>
                        </div>
                     </div>
                </div>   
                <div class="column">
                    <%= form_with model: Message.new do |f| %>
                        <%= f.hidden_field :receiver_id, value: @user.id %>
                        <div class="card-content">
                            <div class="field">
                                <div class="control">
                                    <%= f.text_area :content, class: "textarea" %>
                                </div>
                            </div>
                            <%= f.submit "Send", class: "button is-danger is-pulled-right" %>
                        </div>
                    <% end %>
                </div>
            </div>
        </section>
    </div>
</div>
<script>
    var toggle_modals = $('.toggle-contact');
    if (toggle_modals) {
        toggle_modals.on('click', function(event) {
            event.stopPropagation();
            event.preventDefault();
            var form = document.getElementById('contact-form');
            form.classList.toggle('is-active');
        });
    }
</script>