config/routes.rb
Rails.application.routes.draw do
 
  get 'message/create'
  root 'pages#home'
  
  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show', as: 'users'
  get '/creating_challenges', to: 'challenges#creating_challenges'
  get '/challenging_challenges', to: 'challenges#challenging_challenges'
  get '/challenges/:id', to: 'challenges#show', as: "challenge_detail"
  
  get '/all_requests', to: 'requests#list'
  get '/request_offers/:id', to: 'requests#offers', as: 'request_offers'
  get '/my_offers', to: 'requests#my_offers'
  get '/search', to: 'pages#search'
  get '/calendar', to: 'pages#calendar'
  get '/fixtures/:id/checkout/:detailing_type', to: 'fixtures#checkout', as: 'checkout'
  get '/conversations', to: 'conversations#list', as: "conversations"
  get '/conversations/:id', to: 'conversations#show', as: "conversation_detail"
 
 
 
  post '/users/edit', to: 'users#update'
  post '/offers', to: 'offers#create'
  post '/reviews', to: 'reviews#create'
  post 'messages', to: 'messages#create'
  post '/comments', to: 'comments#create'
  
  put '/creating_challenges/:id/accepted', to: 'challenges#accepted', as: 'challenge_accepted'
  put '/creating_challenges/:id/rejected', to: 'challengess#rejected', as: 'challenge_rejected'
  put '/offers/:id/accept', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'

  
  mount ActionCable.server => '/cable'
 
 
 resources :fixtures do
    member do
      delete :delete_photo
      post :upload_photo
    end
    resources :challenges, only: [:create]
  end
   
   resources :requests
   
  devise_for :users, 
              path: '', 
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
 
  
end

app/views/shared/_categories.html.erb
<nav class="navbar has-shadow" style="z-index: 5">
    <div class="container">
        <div class="navbar">
            <% @categories.each do |item| %>
              <%= link_to "#{item.name}", search_path(category: item.id), class: "navbar-item" %>
            <% end %>
        </div>
    </div>
</nav>

app/views/shared/_fixtures.html.erb
<% @fixtures.each do |fixture| %>

    <div class="column is-one-third">
        <div class="card">

            <div class="card-image">
                <%= link_to fixture_path(fixture) do %>
                    <figure class="image is-4by3">
                        <%= image_tag fixture_cover(fixture) %>
                    </figure>
                <% end %>
            </div>

            <div class="card-content p-t-5 p-b-5">
                <p class="subtitle is-6 m-b-5"><%= link_to fixture.title.truncate(20), fixture_path(fixture) %></p>
                <span class="star-review"><i class="fa fa-star"></i>
                    <%= fixture.average_rating %>
                    <span class="has-text-primary">(<%= fixture.reviews.count %>)</span>
                </span>                                        
            </div>

            <footer class="card-footer">
                <span class="card-footer-item">
                    <%= link_to users_path(fixture.user) do %>
                        <figure class="image is-32x32">
                            <%= image_tag avatar_url(fixture.user), class: "is-rounded" %>
                        </figure>
                    <% end %>
                </span>
                <a class="has-text-danger is-block card-footer-item has-text-right">
                     <span class="small-title">Age Group:</span>  <br>
                    <strong> Under : <%= fixture.age %>'s</strong>
                </a>
            </footer>  
            
        </div>
    </div>

<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar is-warning" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="/">
            <img src="/assets/ruckit-white.png" alt="Logo">
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            <div class="navbar-item">
                <%= form_tag search_path, method: :get do %>
                    <div class="field has-addons <%= 'is-hidden' if current_page?(root_path) %>">
                        <div class="control has-icons-left">
                            <span class="icon is-small is-left">
                                <i class="fa fa-search"></i>
                            </span>
                            <%= text_field_tag 'q', '', class: "input", placeholder: "Try 'Youth Teams" %>
                        </div>
                        <div class="control">
                            <button class="button is-danger" type="submit">Search</button>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>

        <div class="navbar-end">
            <%= link_to 'Create Fixture', new_fixture_path, class: "navbar-item" %>
            <%= link_to 'Browse Fixtures', search_path, class: "navbar-item" %>

            <% if (!user_signed_in?) %>
                <div class="navbar-item">
                    <div class="buttons">
                        <%= link_to  "Sign Up", new_user_registration_path, class: "button is-primary" %>
                        <%= link_to  "Login", new_user_session_path, class: "button is-light" %>
                    </div>
                </div>
            <% else %>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                        <figure class="image is-24x24 m-r-5 avatar <%= current_user.status ? "online" : "offline" %>">
                            <%= image_tag avatar_url(current_user), class: "is-rounded" %>
                        </figure>
                        <%= current_user.full_name %>
                    </a>

                    <div class="navbar-dropdown">
                        <%= link_to  "Profile", edit_user_registration_path, class: "navbar-item" %>
                        <%= link_to 'Dashboard', dashboard_path, class: "navbar-item" %>
                        <hr class="navbar-divider">
                        <%= link_to  "Log out", destroy_user_session_path, method: :delete, class: "navbar-item" %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</nav>

<% if (user_signed_in?) && !current_page?(root_path) && !current_page?(search_path) && !current_page?("/fixtures/#{params[:id]}") && !current_page?("/users/#{params[:id]}") %>
    <nav class="navbar has-shadow" style="z-index: 5">
        <div class="container">
            <div class="navbar">
                <%= link_to 'Dashboard', dashboard_path, class: "navbar-item" %>
                 <%= link_to 'Calendar', calendar_path, class: "navbar-item" %>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Fixture's</a>
                    <div class="navbar-dropdown">
                        <%= link_to 'Create Fixture', new_fixture_path, class: "navbar-item" %>
                    </div>
                </div>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Challenge's</a>
                    <div class="navbar-dropdown">
                        <%= link_to 'Create Challenge', new_request_path, class: "navbar-item" %>
                        <%= link_to 'Manage Replies', requests_path, class: "navbar-item" %>
                    </div>
                </div>
             <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Challenge Requests</a>
                    <div class="navbar-dropdown">
                        <%= link_to 'Active Requests', all_requests_path, class: "navbar-item" %>
                        <%= link_to 'Manage Replies', my_offers_path, class: "navbar-item" %>
                    </div>
                </div> 
				<div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">Fixture Requests</a>
                    <div class="navbar-dropdown">
                        <%= link_to 'Active Requests', creating_challenges_path, class: "navbar-item" %>
                        <%= link_to 'Fixture Confirmations', challenging_challenges_path, class: "navbar-item" %>
                    </div>
                </div>
           
                <%= link_to 'Messages', conversations_path, class: "navbar-item" %>
               
                    </div>
                </div>
      
    </nav>
<% end %>

<script>


$(document).ready(function() {

  // Check for click events on the navbar burger icon
  $(".navbar-burger").click(function() {

      // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
      $(".navbar-burger").toggleClass("is-active");
      $(".navbar-menu").toggleClass("is-active");

  });
});
</script>

app/views/shared/_notification.html.erb
<% unless flash.empty? %>
    <script>
        <% flash.each do |key, value| %>
          <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
          new Noty ({
              type: '<%= type %>',
              layout: 'topRight',
              timeout: '3000',
              theme: 'sunset',
              text: '<%= value %>'
          }).show();
        <% end %>
    </script>
<% end %>