config/routes.rb
Rails.application.routes.draw do
 
  get 'message/create'
  root 'pages#home'
  
  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show', as: 'users'
  get '/creating_challenges', to: 'challenges#creating_challenges'
  get '/challenging_challenges', to: 'challenges#challenging_challenges'
  get '/challenges/:id', to: 'challenges#show', as: "challenge_detail"
  
  get '/all_requests', to: 'requests#list'
  get '/request_offers/:id', to: 'requests#offers', as: 'request_offers'
  get '/my_offers', to: 'requests#my_offers'
  get '/search', to: 'pages#search'
  get '/calendar', to: 'pages#calendar'
  get '/fixtures/:id/checkout/:detailing_type', to: 'fixtures#checkout', as: 'checkout'
  get '/conversations', to: 'conversations#list', as: "conversations"
  get '/conversations/:id', to: 'conversations#show', as: "conversation_detail"
 
 
 
  post '/users/edit', to: 'users#update'
  post '/offers', to: 'offers#create'
  post '/reviews', to: 'reviews#create'
  post 'messages', to: 'messages#create'
  post '/comments', to: 'comments#create'
  
  put '/creating_challenges/:id/accepted', to: 'challenges#accepted', as: 'challenge_accepted'
  put '/creating_challenges/:id/rejected', to: 'challengess#rejected', as: 'challenge_rejected'
  put '/offers/:id/accept', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'

  
  mount ActionCable.server => '/cable'
 
 
 resources :fixtures do
    member do
      delete :delete_photo
      post :upload_photo
    end
    resources :challenges, only: [:create]
  end
   
   resources :requests
   
  devise_for :users, 
              path: '', 
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
 
  
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
  belongs_to :category
  
  has_one_attached :attachment_file
  has_many :offers, dependent: :delete_all
  has_many :challenges
  
  validates :title, presence: { message: "cannot be empty" }
  validates :description, presence: { message: "cannot be empty" }
  validates :location, presence: { message: "cannot be empty" }
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_request, except: [:new, :create, :index, :list, :my_offers]
  before_action :is_authorised, only: [:edit, :update, :destroy, :offers]
  before_action :set_categories, only: [:new, :edit, :list]
  
  def index
    @requests = current_user.requests
  end

  def new
    @request = current_user.requests.build
  end

  def create
    @request = current_user.requests.build(request_params)
    if @request.save
      redirect_to requests_path, notice: "Saved..."
    else
      redirect_to request.referrer, flash: {error: @request.errors.full_messages.join(', ')}
    end
  end

  def edit
  end

  def update
    if @request.update(request_params)
      redirect_to requests_path, notice: "Saved..."
    else
      redirect_to request.referrer, flash: {error: @request.errors.full_messages.join(', ')}
    end
  end

  def show
  end

  def destroy
    @request.destroy
    redirect_to requests_path, notice: "Removed..."
  end

  def list
    @category_id = params[:category]

    if @category_id.present?
      @requests = Request.where(category_id: @category_id)
    else
      @requests = Request.all
    end
  end
  
  def offers
    @offers = @request.offers
  end

  def my_offers
    @offers = current_user.offers
  end
 
 
  private
  
  def set_categories
    @categories = Category.all
  end
  
  def set_request
    @request = Request.find(params[:id])
  end
 
  def is_authorised
    redirect_to root_path, alert: "You don't have permission" unless current_user.id == @request.user_id
  end
  
  def request_params
    params.require(:request).permit(:description, :category_id, :location, :age, :attachment_file, :title)
  end
  
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/edit.html.erb
<section class="section">
    <div class="container">
        <div class="form-container">
            <p class="title is-4 has-text-centered">Create your Challenge</p>
<p class="subtitle has-text-centered">Give details of what kind of challenge your looking for </p>
            <%= form_for @request do |f| %>
                <div class="field">
                    <label class="label">Title (*)</label>
                    <%= f.text_field :title, placeholder: "I request...", class: "input" %>
                </div>
                <div class="field">
                    <label class="label">Description (*)</label>
                    <%= f.text_area :description, placeholder: "I'm looking for...", class: "textarea" %>
                </div>
                <div class="field">
                    <label class="label">Choose a category</label>
                    <div class="select is-fullwidth">
                        <%= f.select(:category_id, options_for_select(@categories.map { |c| [c.name, c.id] }, selected: @request.category_id)) %>
                    </div>
                </div>
                <div class="field">
                    <label class="label">Location</label>
                    <%= f.text_area  :location, placeholder: "Munster", class: "textarea" %>
                </div>
                
                <div class="field">
                    <label class="label">Upload attachment (Optional)</label>
                    <div class="file is-warning has-name">
                        <label class="file-label">
                            <%= f.file_field :attachment_file, class: "file-input" %>
                            <span class="file-cta"><span class="file-label">Choose a file...</span></span>
                            <span class="file-name" id="file-name">No file selected</span>
                        </label>
                    </div>
                </div>

                <% if @request.attachment_file.attached? %>
                    <p>
                        <%= link_to url_for(@request.attachment_file), 
                                        class: "tag small is-warning m-t-20",  
                                        download: "Attachment_#{@request.attachment_file.id}" do %>
                            <i class="fas fa-paperclip fa-lg p-r-5"></i> <%= @request.attachment_file.filename %>

                        <% end %>
                    </p>
                <% end %>

                <div class="field has-text-centered">
                    <%= f.submit 'Update request', class: "button is-primary" %>
                </div>
              
            <% end %>
        </div>
    </div>
</section>

<script>
    $(document).ready(function() {
        var file = $('.file-input');
        file.change(function(e) {
            if (file[0].files.length > 0) {
                var attachment = file[0].files[0];
                $('.file-name').text(attachment.name + " (" + attachment.size + " bytes)");
            }
        })
    })
</script>

app/views/requests/index.html.erb
<section class="section">
    <div class="container">
       <p class="title">Manage Replies</p>
        <p class="subtitle">to your Challenge</p>
            <%= link_to 'Post new request', new_request_path, class: "button is-primary is-pulled-right"%>
        </p>

        <table class="table is-fullwidth">
            <thead class="is-centered">
                <tr>
                    <td>Location</td>
                    <td>Request</td>
                    <td class="has-text-right">Offers</td>
                    <td class="has-text-right">Action</td>
                </tr>
            </thead>
            <tbody>
                <% if @requests.blank? %>
                    <tr>
                        <td colspan="4" class="has-text-centered"><h1>NOTHING TO SHOW HERE</h1></td>
                    </tr>
                <% end %>
                <% @requests.each do |r| %>
                    <tr>
                        <td><%= r.created_at.strftime('%d, %b %Y') %></td>
                        <td><%= link_to r.title, request_path(r) %></td>
                        <td class="has-text-right">
                            <%= link_to r.offers.count, request_offers_path(r) %>
                        </td>
                        <td class="has-text-right">
                            <%= link_to edit_request_path(r), class: "m-r-5" do %>
                                <span class="icon has-text-success">
                                    <i class="far fa-edit fa-lg"></i>
                                </span>
                            <% end %>

                            <%= link_to r, method: :delete, data: {confirm: "Are you sure?"} do %>
                                <span class="icon has-text-danger">
                                    <i class="far fa-trash-alt fa-lg"></i>
                                </span>
                            <% end %>
                        </td>
                    </tr>
                <% end %>
            </tbody>

        </table>
    
    </div>
</section>

app/views/requests/list.html.erb
<section class="section">
    <div class="container">
        <p class="title">
            Active Challenge Requests
            <%= link_to 'Post a request', new_request_path, class: "button is-primary is-pulled-right" %>
        </p>
        <div class="card">
            <div class="card-header">
                <%= form_tag '', method: :get do %>
                    <div class="field p-10">
                        <div class="select">
                            <%= select_tag 'category', content_tag(:option, 'All Categories', value: "") + 
                                                        options_for_select(@categories.map { |c| [c.name, c.id] }, 
                                                        selected: @category_id),
                                                        onchange: "this.form.submit();" %>
                        </div>
                    </div>
                <% end %>
            </div>
            <div class="card-content">

                <table class="table is-fullwidth">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Challenger</th>
                            <th>Request</th>
                            <th>Team</th>
                            <th>Age</th>
                            <th class="has-text-centered">Offers</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% if @requests.blank? %>
                            <tr>
                                <td colspan="6" class="has-text-centered"><h1>NOTHING TO SHOW HERE</h1></td>
                            </tr>
                        <% end %>
                        <% @requests.each do |r| %>
                            <tr>
                                <td><%= r.created_at.strftime('%d, %b %Y') %></td>
                                <td>
                                    <figure class="image is-48x48">
                                        <%= image_tag avatar_url(r.user), class: "is-rounded" %>
                                    </figure>
                                </td>
                                <td>
                                    <%= link_to request_path(r), class: "tootip" do %>
                                        <label for="" class="tooltip" data-tooltip="<%= r.description %>">
                                            <%= r.description.truncate(25, seperator: ' ') %>
                                        </label>
                                    <% end %>
                                </td>
                                <td><%= r.title %></td>
                                <td>Under<%= pluralize(r.age,'s') %></td>
                                <td class="has-text-centered"><%= r.offers.count %></td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</section>

app/views/requests/my_offers.html.erb
<section class="section">
    <div class="container">
        <p class="title">Manage Replies</p>
        <p class="subtitle">you made to Challenges</p>
        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Challenger</th>
                    <th>Team</th>
                    <th>Date</th>
                    <th>Location</th>
                    <th>Age</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                <% if @offers.blank? %>
                    <tr>
                        <td colspan="6" class="has-text-centered"><h1>NOTHING TO SHOW HERE</h1></td>
                    </tr>
                <% end %>
                <% @offers.each do |o| %>
                    <tr>
                        <td><%= o.created_at.strftime('%d, %b %Y') %></td>
                        <td>
                            <figure class="image is-48x48">
                                <%= image_tag avatar_url(o.user), class: "is-rounded" %> 
                            </figure>
                        </td>
                        
                        <td>
                            <%= link_to o.request.title, request_path(o.request) %>
                        </td>
                        <td><%= o.request.created_at.strftime('%d, %b %Y') %></td>
                        <td><%= o.location %></td>
                        <td><%= o.age %></td>
                       <td>
                           <span class="tag <%= 'is-warning' if o.pending? %>
                                            <%= 'is-success' if o.accepted? %>
                                            <%= 'is-danger' if o.rejected? %> ">
                                            <%= o.status.capitalize %>
                           </span>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</section>

app/views/requests/new.html.erb
<section class="section">
    <div class="container">
        <div class="form-container">
                <p class="title is-4 has-text-centered">Create your Challenge</p>
<p class="subtitle has-text-centered">Give details of what kind of challenge your looking for </p>

            <%= form_for @request do |f| %>
                <div class="field">
                    <label class="label">Club Name(*)</label>
                    <%= f.text_field :title, placeholder: "Club Name ", class: "input" %>
                </div>
                <div class="field">
                    <label class="label">Challenge Description (*)</label>
                    <%= f.text_area :description, placeholder: "I'm looking for a friendly against a mixed aged team of new players", class: "textarea" %>
                </div>
                <div class="field">
                    <label class="label">Choose a age category</label>
                    <div class="select is-fullwidth">
                        <%= f.select(:category_id, options_for_select(@categories.map { |c| [c.name, c.id] })) %>
                    </div>
                </div>
                <div class="field">
                    <label class="label">Location of fixture</label>
                    <%= f.text_area  :location, placeholder: "we can travel any where in Munster", class: "textarea" %>
                </div>
                <div class="field">
                    <label class="label">Age</label>
                    <%= f.number_field :age, placeholder: "Under 13's", class: "input" %>
                </div>
                <div class="field">
                    <label class="label">Upload attachment (Optional)</label>
                    <div class="file is-warning has-name">
                        <label class="file-label">
                            <%= f.file_field :attachment_file, class: "file-input" %>
                            <span class="file-cta"><span class="file-label">Choose a file...</span></span>
                            <span class="file-name" id="file-name">No file selected</span>
                        </label>
                    </div>
                </div>

                <div class="field has-text-centered">
                    <%= f.submit 'Post Request', class: "button is-primary" %>
                </div>
              
            <% end %>
        </div>
    </div>
</section>

<script>
    $(document).ready(function() {
        var file = $('.file-input');
        file.change(function(e) {
            if (file[0].files.length > 0) {
                var attachment = file[0].files[0];
                $('.file-name').text(attachment.name + " (" + attachment.size + " bytes)");
            }
        })
    })
</script>

app/views/requests/offers.html.erb
<section class="section">
    <div class="container">
        <p class="title">View Challenge Offers</p>
        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Creator Name</th>
                    <th>Notes</th>
                    <th>Club</th>
                    <th>Age</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <% if @offers.blank? %>
                    <tr>
                        <td colspan="7" class="has-text-centered"><h1>NOTHING TO SHOW HERE</h1></td>
                    </tr>
                <% end %>
                <% @offers.each do |o| %>
                    <tr>
                        <td><%= o.created_at.strftime('%d, %b %Y') %></td>
                        <td>
                            <figure class="image is-48x48">
                                <%= image_tag avatar_url(o.user), class: "is-rounded" %>
                            </figure>
                        </td>
                        <td><%= o.note %></td>
                        <td><%= link_to o.request.title, request_path(o.request) %></td>
                        <td>Under<%= o.age %>'s</td>
                        <td>
                            <span class="tag <%= 'is-warning' if o.pending? %> 
                                             <%= 'is-success' if o.accepted? %>
                                             <%= 'is-danger' if o.rejected? %> ">
                                <%= o.status.capitalize %>
                            </span>
                        </td>
                        <td>
                            <%= link_to accept_offer_path(o), method: :put,
                                        data: { confirm: "Are you sure?" },
                                        class: "button is-small is-primary is-outlined #{'is-hidden' if !o.pending?}" do %>
                                <span class="icon"><i class="far fa-check-circle fa-lg"></i></span>
                                <span>Accept</span>
                            <% end %>

                            <%= link_to reject_offer_path(o), method: :put,
                                        data: { confirm: "Are you sure?" },
                                        class: "button is-small is-danger is-outlined #{'is-hidden' if !o.pending?}" do %>
                                <span class="icon"><i class="far fa-times-circle fa-lg"></i></span>
                                <span>Reject</span>
                            <% end %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</section>

app/views/requests/show.html.erb
<section class="section">
    <div class="container">
        <div class="columns">

            <!-- LEFT SIDE -->
            <div class="column is-two-thirds">
                <div class="columns is-multiline">

                    <!-- Title -->
                    <div class="column is-full">
                        <p class="title is-4"><%= @request.title %></p>
                        <article class="media">
                            <div class="media-content">
                                <p>
                                    <%= @request.category.name %>
                                    <span class="is-pulled-right">Posted on: <%= @request.created_at.strftime('%d, %b %Y') %></span>
                                </p>
                                Fixtures Location: <%= @request.location %> | Offers: <%= @request.offers.count %> | Age: Under<%= @request.age %>'s
                            </div>
                        </article>
                    </div>

                    <!-- Description -->
                    <div class="column is-full">
                        <div class="card">
                            <div class="card-content">
                                <strong>Description</strong>
                                <hr>
                                <%= @request.description %>
                                <% if @request.attachment_file.attached? %>
                                    <p>
                                        <%= link_to url_for(@request.attachment_file), 
                                                class: "tag small is-warning m-t-20",
                                                download: "Attachment_#{@request.attachment_file.id}" do %>

                                            <i class="fas fa-paperclip fa-lg p-r-5"></i><%= @request.attachment_file.filename %>
                                        <% end %>
                                    </p>
                                <% end %>
                            </div>
                        </div>
                    </div>

                    <!-- About Challenger -->
                    <div class="column">
                        <div class="card">
                            <div class="card-content">
                                <strong>About the Challenger</strong> 
                                <hr/>

                                <div class="content">
                                    <div class="columns">

                                        <!-- Challenger Avatar -->
                                        <div class="column">
                                            <div class="card-content is-horizontal-center is-flex">
                                                <figure class="image is-96x96">
                                                    <%= image_tag avatar_url(@request.user), class: "is-rounded" %>
                                                </figure>
                                            </div>
                                            
                                            
                                            
                                            
                                            
                                              
                                <div class="content has-text-centered">
                                    <p class="title is-5"><%= @request.user.full_name %></p>
                                        <% if current_user.id != @request.user.full_name%>
                                        <a class="button is-black is-outlined is-fullwidth toggle-contact">Contact Me</a>
                                        <% end %>
                                </div>
                                            
                                            
                                            
                                            
                                            
                                        </div>

                                        <!-- Challenger Profile -->
                                        <div class="column f-15">

                                            <article class="media">
                                                <div class="media-content">
                                                    <i class="fas fa-user m-r-5"></i> Member since
                                                </div>
                                                <div class="media-right">
                                                    <%= @request.user.created_at.strftime('%b %Y') %>
                                                </div>
                                            </article>
                                            <article class="media">
                                                <div class="media-content">
                                                    <i class="fas fa-map-marker-alt m-r-5"></i> From
                                                </div>
                                                <div class="media-right">
                                                    <%= @request.user.from %>
                                                </div>
                                            </article>
                                            <article class="media">
                                                <div class="media-content">
                                                    <%= @request.user.about %>
                                                </div>
                                            </article>
                                            
                                        </div>

                                    </div>
                                </div>

                                    
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>

            <!-- RIGHT SIDE -->
            <div class="column">
                <div class="card">
                    <%= form_for Offer.new do |f| %>
                      
                        <div class="card-content">
                            <%= f.hidden_field :request_id, value: @request.id %>
                             <div class="field">
                                <label for="" class="label">Club Name</label>
                                <%= f.text_field :club, class: "input" %>
                            </div>
                            <div class="field">
                                <label for="" class="label">Age Group (Under)</label>
                                <%= f.text_field :age, class: "input" %>
                            </div>
                           <div class="field">
                                <label for="" class="label">Date (Available to Play)</label>
                                <%= f.date_field :date, class: "input" %>
                            </div>
                            <div class="field">
                                <label for="" class="label">Location</label>
                                <%= f.text_field :location, class: "input" %>
                            </div>
                            <div class="field">
                                <label for="" class="label">Challenge note</label>
                                <%= f.text_area :note, class: "textarea" %>
                            </div>
                            <%= f.submit 'Send Challenge', class: "button is-primary is-fullwidth" %>

                        </div>

                    <% end %>
                </div>
            </div>

        </div>
    </div>
</section>
<div class="modal" id="contact-form">
    <div class="modal-background"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title">Send a Message</p>
            <button class="delete toggle-contact" aria-label="close"></button>
        </header>
        <section class="modal-card-body">
            <div class="columns">
                <div class="column is-one-third">
                    <div class="card">
                        <div class="card-content is-horizontal-center is-flex">
                            <figure class="image is-128x128">
                                <%= image_tag avatar_url(@request.user), class: "is-rounded" %>
                            </figure>
                        </div>
                        <div class="card-content">
                            <hr>
                            <strong>Please include:</strong>
                            <ul class="is-size-7" style="list-style:initial">
                                <li>Any Questions you have about this fixture</li>
                                <li>along with some details about your Team</li>
                                <li>your time frame & location</li>
                            </ul>
                        </div>
                     </div>
                </div> 
                  
                
                <div class="column">
                    <%= form_with model: Message.new do |f| %>
                        <%= f.hidden_field :receiver_id, value: @request.user.id %>
                        <div class="card-content">
                            <div class="field">
                                <div class="control">
                                    <%= f.text_area :content, class: "textarea" %>
                                </div>
                                
                                
                                
                            </div>
                            <%= f.submit "Send", class: "button is-danger is-pulled-right" %>
                        </div>
                    <% end %>
                </div>
            </div>
        </section>
    </div>
</div>
<script>
    var toggle_modals = $('.toggle-contact');
    if (toggle_modals) {
        toggle_modals.on('click', function(event) {
            event.stopPropagation();
            event.preventDefault();
            var form = document.getElementById('contact-form');
            form.classList.toggle('is-active');
        });
    }
</script>


<script>
    BulmaCarousel.attach('#carousel-photo', {
        slidesToScroll: 1,
        slidesToShow: 1
    });

    $(document).ready(function() {
        $('#tabs li').on('click', function() {
            var type = $(this).data('tab');

            $('#tabs li').removeClass('is-active');
            $(this).addClass('is-active');

            $('.tab-content').hide();
            $('#tab-' + type).show();
        }) 
    })

</script>